blog/about/urls.py
from django.urls import path
from about import views

urlpatterns = [
    path("", views.about, name ="about"),
    path("melina/", views.melina, name ="melina"),
    path("pablo/", views.pablo, name ="pablo"),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blogprincipal.urls')),
    path('user/', include('users.urls')),
    path('about/', include('about.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blogprincipal/urls.py
from django.conf.urls.static import static
from django.urls import path
from blogprincipal import views

urlpatterns = [
    path("", views.home, name ="home"),
    path("listar/", views.BlogList.as_view(), name ="listar"),
    path("detalle/<pk>", views.BlogDetalle.as_view(), name ="detalle"),
    path("crear/", views.BlogCrear.as_view(), name ="crear"),
    path("actualizar/<pk>/", views.BlogActualizar.as_view(), name ="actualizar"),
    path("borrar/<pk>/", views.BlogBorrar.as_view(), name ="borrar"),
    path("entrar/", views.BlogLogin.as_view(), name="entrar"),
    path("salir/", views.BlogLogout.as_view(), name="salir"),
    path("error/", views.error, name="error"),
]

blog/users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from users import views

urlpatterns = [
    path("crear", views.SingUpUser.as_view(), name ="crear_usuario"),
    path("perfil/<pk>/", views.UserPerfil.as_view(), name ="perfil"),
    path("editar/<pk>", views.UserModificar.as_view(), name ="editar"),
    path("cargaravatar/<pk>", views.AvatarCrear.as_view(), name ="cargar_avatar"), 
]

blog/about/models.py
from django.db import models

# Create your models here.

blog/blogprincipal/models.py
from django.db import models
from django.contrib.auth.models import User


class Blog(models.Model):
    titulo = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=100)
    contenido = models. TextField()
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha_creacion = models.DateField(auto_now_add=True)
    image = models.ImageField(upload_to="fotos", null=True, blank=True)

    def __str__(self):
        return self.titulo

blog/users/models.py
from django.db import models
from django.contrib.auth.models import User



class Avatar(models.Model):
    blog = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="avatars", null=True, blank=True)

blog/users/forms.py
from dataclasses import fields
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UsuarioForm(UserCreationForm):
    class Meta:
        model = User
        fields = [ 'first_name','last_name','username', 'email', 'password1', 'password2' ] 

blog/about/views.py
from django.shortcuts import render

def about(request):
    return render(request, "about/about.html")

def melina(request):
    return render(request, "about/melina.html")

def pablo(request):
    return render(request, "about/pablo.html")

blog/blogprincipal/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from blogprincipal.models import *
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import PermissionDenied


def home(request):
    return render(request, "blogprincipal/home.html")

def error(request):
    return render(request, "blogprincipal/error.html")

class BlogList(ListView):
    model = Blog
    template_name = "blogprincipal/listar.html"

class BlogDetalle(DetailView):
    model = Blog 
    template_name = "blogprincipal/detalle.html"

class BlogCrear(LoginRequiredMixin,CreateView):
    model = Blog
    success_url = "/blog/listar"
    template_name = "blogprincipal/crear.html"
    fields = ["titulo", "descripcion", "contenido", "image"]    

    def form_valid(self, form):
        form.instance.autor = self.request.user
        return super().form_valid(form)

class BlogActualizar(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = Blog
    success_url = "/blog/listar"
    template_name = "blogprincipal/actualizar.html"
    fields = ["titulo", "descripcion", "contenido", "image"] 

    def test_func(self):
        exist = Blog.objects.filter(autor=self.request.user.id, id=self.kwargs['pk'])
        return True if exist else False
    def handle_no_permission(self):
        return  redirect("/blog/error") 
    

class BlogBorrar(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = Blog
    success_url = "/blog/listar" 
    template_name = "blogprincipal/borrar.html"

    def test_func(self):
        exist = Blog.objects.filter(autor=self.request.user.id, id=self.kwargs['pk'])
        return True if exist else False    
    def handle_no_permission(self):
        return  redirect("/blog/error") 


class BlogLogin(LoginView):
    template_name = 'blogprincipal/login.html'
    success_url = "/blog/home" 
    next_page = reverse_lazy("home")

class BlogLogout(LogoutView):
    template_name = 'blogprincipal/logout.html' 

blog/users/views.py
from django.shortcuts import render
from django.views.generic import CreateView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from users.forms import UsuarioForm
from users.models import Avatar


class SingUpUser(CreateView):
    template_name = "users/crear_cuenta.html"
    success_url = reverse_lazy('entrar')
    form_class = UsuarioForm 
    success_message = " Se creo tu usuario en mi pagina web "

class UserPerfil(DetailView):
    model = User 
    template_name = "users/perfil.html"

class UserModificar(LoginRequiredMixin, UpdateView):

    model = User
    template_name = "users/editar.html"
    fields = ['first_name','last_name','username', 'email',]

    def get_success_url(self):
      return reverse_lazy("perfil", kwargs={"pk": self.request.user.id})

class AvatarCrear(LoginRequiredMixin,CreateView):
    model = Avatar
    success_url = reverse_lazy('home')
    template_name = "users/cargar_avatar.html"
    fields = ["blog", "image"]    

    def form_valid(self, form):
        form.instance.autor = self.request.user
        return super().form_valid(form)

blog/about/templates/about/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
</head>
<body>
    <p>Este es un blog creado por Melina y Pablo como entrega final del curso de python de coder house</p>
    <p>Puedes saber mas de cada uno aqui:</p>
    <a href="{% url 'melina' %}"> About Melina</a>
    <a href="{% url 'pablo' %}">Ablut Pablo</a>
    <p></p>
    <a href="{% url 'home' %}">Volver al blog</a>
</body>
</html>

blog/about/templates/about/melina.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Melina</title>
</head>
<body>
    <p>Mi nombre es Melina Tarquini, tengo 23 años y soy de Córdoba, Argentina. Estoy en el último año de Ingeniería Industrial y soy pasante del área de Compras en una automotriz. Comencé el curso sin saber nada de programación, y lo hice con el objetivo de complementar mi carrera y a su vez porque me entusiasma la idea de programar. Junto con mi compañero hicimos la entrega final, la cual se trata de un blog donde los usuarios pueden crear y editar sus blogs. Yo me encargué principalmente de la aplicación users, creando las vistas, urls, modelos y templates.   </p>
    <a href="{% url 'about' %}">volver</a>
</body>
</html>

blog/about/templates/about/pablo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pablo</title>
</head>
<body>
    <p>Me llamo Pablo Bejarano, tengo 27 años y soy de Bogotá Colombia, soy ingeniero en automatización industrial y actualmente trabajo como ingeniero DevOps especializado en la nube de AWS en Globant, decidí iniciar el curso de Python porque tenía el deseo de entender el lenguaje para poder aplicarlo en mi dia a dia como devops y poder automatizar tareas, encontré en el curso algo nuevo para mí como es el desarrollo web lo cual me parece interesante y género en mi muchas más dudas y deseos de aprender todo lo que se puede hacer con Python</p>
    <a href="{% url 'about' %}">volver</a>
</body>
</html>

blog/blogprincipal/templates/blogprincipal/actualizar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }} 
        <input type="submit" value="Enviar" > 
        <a href="{% url 'detalle' blog.id %}" >cancelar</a>
    </form>
</body>
</html>

blog/blogprincipal/templates/blogprincipal/borrar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        <p>¿Está Seguro que quiere borrar "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="Confirmar">
        <a href="{% url 'detalle' blog.id %}" >cancelar</a>

    </form> 
</body>
</html>

blog/blogprincipal/templates/blogprincipal/crear.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }} 
        <input type="submit" value="Enviar" > 
        <a href="{% url 'home' %}" >cancelar</a>
    </form>
</body>
</html>

blog/blogprincipal/templates/blogprincipal/detalle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>detalle blog</title>
</head>
<body>
    <h1 style="text-align: center;"><strong><i>{{ blog.titulo }}</i></strong></h1>
    <p><strong>Descripcion</strong></p>
    <p><i>{{ blog.descripcion }}</i></p>
    <p><strong>Contenido</strong></p>
    <p><i>{{ blog.contenido }}</i></p> 
    <img height="400" src="{{ blog.image.url }}"></img>
    <p>Autor del blog: <i>{{ blog.autor }}</i> </p>
    <p>Fecha de creacion: <i>{{ blog.fecha_creacion }}</i> </p>
    {% if user.is_authenticated %}
        <a href="{% url 'listar' %}">Blogs</a>
        <a href="{% url 'actualizar' blog.id %}">editar</a>
        <a href="{% url 'borrar' blog.id %}">borrar</a>
    {% else %}
        <a href="{% url 'listar' %}">Blogs</a>
    {% endif %}
</body>
</html>

blog/blogprincipal/templates/blogprincipal/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>No esta autorizado a realizar esta accion</h1>
        <a href="{% url 'listar' %}">volver a los blogs </a>
        <a href="{% url 'salir' %}">salir</a> </a>
</body>
</html>

blog/blogprincipal/templates/blogprincipal/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <a href="{% url 'about' %}">Acerca de los creadores</a>
    <h1>Bienvenido al blog de Melina y Pablo</h1>
    {% if user.is_authenticated %}
        <a href="{% url 'listar' %}">Listar blogs</a>
        <a href="{% url 'crear' %}">crear blog</a>
        <a href="{% url 'perfil' user.id %}">ver perfil</a>
        <a href="{% url 'salir' %}">salir</a>
        
    {% else %}
    <a href="{% url 'listar' %}">Listar blogs</a>
    <a href="{% url 'entrar' %}">ingresar</a>
    <a href="{% url 'crear_usuario' %}">Crear usuario</a>
    {% endif %}
    
</body>
</html>

blog/blogprincipal/templates/blogprincipal/listar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listar blog</title>
</head>
<body>
    <ul>
        {% for blog in object_list %}
            <li>
                <p> Nombre: {{ blog.titulo }}</p>
                <p> Descripcion: {{ blog.descripcion }}</p>
                <p> Autor: {{ blog.autor }}</p>
                <p> Creacion: {{ blog.fecha_creacion }}</p>
                <a href="{% url 'detalle' blog.id %}">ver</a>
            </li>
        {% endfor %}        
    </ul>
    <a href="{% url 'home' %}">home</a>
</body>
</html>

blog/blogprincipal/templates/blogprincipal/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>   
    <form method="POST">{% csrf_token %}
        {{form.as_p}}
    <button type="submit">Iniciar Sesión</button>
    <a href="{% url 'home' %}">home</a>
</form>
</body>
</html>

blog/blogprincipal/templates/blogprincipal/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Gracias por leernos, vuelve pronto</h1>
    <a href="{% url 'listar' %}">blogs</a>
    <a href="{% url 'home' %}">home</a>
</body>
</html>

blog/users/templates/users/cargar_avatar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }} 
        <input type="submit" value="Enviar" > 
        <a href="{% url 'perfil' user.id %}" >cancelar</a>
    </form>
</body>
</html>

blog/users/templates/users/crear_cuenta.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Crear Cuenta">
    </form>
    <a href="{% url 'home' %}">Cancelar</a>
</body>
</html>

blog/users/templates/users/editar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        {{ form.as_p }} 
        <input type="submit" value="Enviar" > 
        <a href="{% url 'perfil' user.id %}" >cancelar</a>
    </form>
</body>
</html>

blog/users/templates/users/perfil.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
  <ul>
      <li> Nombre: {{ user.first_name }}</li>
      <li> Apellido: {{ user.last_name }}</li>
      <li> Usuario: {{ user.username }}</li>
      <li> Email: {{ user.email }}</li>
      <li> fecha de creacion: {{ user.date_joined }}</li>
      <li> ultima entrada: {{ user.last_login }}</li>
  </ul>

  <img height="128" src="{{ user.avatar_set.first.image.url }}"></img>
  <p></p>
  <a href="{% url 'home' %}">volver</a>
  <a href="{% url 'editar' user.id %}">editar</a>
  <a href="{% url 'cargar_avatar' user.id %}">Cargar/editar avatar</a>
</body>
</html>